### ISSUE TITLE
TypeError: ufunc 'true_divide' output (typecode 'd') could not be coerced to provided output parameter (typecode 'l') according to the casting rule ''same_kind''

### ISSUE THREAD

**Issue by ignatenkobrain** [nipy/nitime#133]
``` python

======================================================================
ERROR: Testing the initialization of the uniform time series object
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/nitime-rel-0.5/nitime/tests/test_timeseries.py", line 545, in test_TimeSeries
    tseries2 /= 2
  File "/builddir/build/BUILD/nitime-rel-0.5/nitime/timeseries.py", line 1021, in __idiv__
    self.data.__itruediv__(other)
TypeError: ufunc 'true_divide' output (typecode 'd') could not be coerced to provided output parameter (typecode 'l') according to the casting rule ''same_kind''
```

**Comment by arokem** [comment]
Thanks for reporting this. I can see this on my machine as well. Must be related to recent changes on numpy.

**Comment by arokem** [comment]
Does #135 resolve this for you?

**Comment by ignatenkobrain** [comment]
@arokem, yes it fixes.

**Comment by effigies** [comment]
Looks fixed.
