### ISSUE TITLE
[i686] nitime.tests.test_timeseries.test_basic_slicing: npt.assert_equal(len(t[ep]), x)

### ISSUE THREAD

**Issue by ignatenkobrain** [nipy/nitime#136]
Fails only on i686:
```python
======================================================================
FAIL: nitime.tests.test_timeseries.test_basic_slicing
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/nitime-rel-0.5/nitime/tests/test_timeseries.py", line 672, in test_basic_slicing
    npt.assert_equal(len(t[ep]), x)
  File "/usr/lib/python3.4/site-packages/numpy/testing/utils.py", line 354, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: 0
 DESIRED: 1
```

**Comment by arokem** [comment]
This one also reproduced on Windows: https://ci.appveyor.com/project/arokem/nitime/build/1.0.7/job/nxvdt73pwxrfq8co

**Comment by sanjayankur31** [comment]
Hiya,

Any update on this? I'm building the latest commit 1fab571 and this test still fails on i686.

**Comment by arokem** [comment]
I'd like to fix this, but I am not sure: How would I go about reproducing this error?

**Comment by sanjayankur31** [comment]
Sorry---I'll try and collect more information and hopefully that'll tell us a little more. On my TODO list now :)

**Comment by alcir** [comment]
Hello. I'm not a Python expert, at all.
I'm running pytest on a RPi3 running an armv7hl system.

In the for loop at line 690 of `test_timeseries.py`
https://github.com/nipy/nitime/blob/07382c057b628f74d47b525d0552b832b59c18df/nitime/tests/test_timeseries.py#L690

when the loop start, `x` is '0' and `len(t[ep])` is `0`
when `x` become 1, `len(t[ep])` is `0` as well, and `npt.assert_equal(len(t[ep]), x)` fails.
