### ISSUE TITLE
pip install problem with numpy

### ISSUE THREAD

**Issue by oesteban** [nipy/nitime#141]
This error happens with numpy installed. It also happens when building in readthedocs projects having nitime as a requirement and autodocs enabled.

```
Collecting numpy (from nitime)
  Using cached numpy-1.10.4-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting nitime
  Downloading nitime-0.6.tar.gz (10.0MB)
    100% |████████████████████████████████| 10.0MB 55kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/hw/7bn8tjn96vd58k7sg1ptt82c0000gn/T/pip-build-l6NHiN/nitime/setup.py", line 17, in <module>
        exec(f.read())
      File "<string>", line 2, in <module>
      File "nitime/__init__.py", line 26, in <module>
        from . import algorithms
      File "nitime/algorithms/__init__.py", line 55, in <module>
        from nitime.algorithms.spectral import *
      File "nitime/algorithms/spectral.py", line 10, in <module>
        import numpy as np
    ImportError: No module named numpy
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/hw/7bn8tjn96vd58k7sg1ptt82c0000gn/T/pip-build-l6NHiN/nitime
```

**Comment by arokem** [comment]
This might have to do with a generally out-dated setup file. Let me take a look.

**Comment by arokem** [comment]
Could you please show me where this is happening, so that I can easily
replicate?

**Comment by rwblair** [comment]
On OS X 10.5 I saw it happen with a fresh python 2.7 virtual env, here are the steps I took:

```
(rblair@PSY-C02Q70WEFY10) :) (14:45)
~/projects $ virtualenv -p python2.7 .venv/nitime_test
Running virtualenv with interpreter /usr/local/bin/python2.7
New python executable in .venv/nitime_test/bin/python2.7
Also creating executable in .venv/nitime_test/bin/python
Installing setuptools, pip, wheel...done.
(rblair@PSY-C02Q70WEFY10) :) (14:45)
~/projects $ source .venv/nitime_test/bin/activate
(nitime_test)(rblair@PSY-C02Q70WEFY10) :) (14:46)
~/projects $ pip install --no-cache nitime
Collecting nitime
  Downloading nitime-0.6.tar.gz (10.0MB)
    100% |████████████████████████████████| 10.0MB 46.5MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/hw/7bn8tjn96vd58k7sg1ptt82c0000gn/T/pip-build-Cya5qp/nitime/setup.py", line 17, in <module>
        exec(f.read())
      File "<string>", line 2, in <module>
      File "nitime/__init__.py", line 26, in <module>
        from . import algorithms
      File "nitime/algorithms/__init__.py", line 55, in <module>
        from nitime.algorithms.spectral import *
      File "nitime/algorithms/spectral.py", line 10, in <module>
        import numpy as np
    ImportError: No module named numpy
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/hw/7bn8tjn96vd58k7sg1ptt82c0000gn/T/pip-build-Cya5qp/nitime
You are using pip version 7.1.2, however version 8.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(nitime_test)(rblair@PSY-C02Q70WEFY10) :( 1 (14:46)
~/projects $ 
```

The pip install step does not appear to collect requirements.

Also tested on Debian 8.3 with similar results:

```
rwblair@afterhours:~$ virtualenv -p python2.7 .venv/nitime_test
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in .venv/nitime_test/bin/python2.7
Also creating executable in .venv/nitime_test/bin/python
Installing setuptools, pip...done.
rwblair@afterhours:~$ source .venv/nitime_test/bin/activate
(nitime_test)rwblair@afterhours:~$ pip install --no-cache nitime
Collecting nitime
  Downloading nitime-0.6.tar.gz (10.0MB)
    100% |████████████████████████████████| 10.0MB 40.3MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Dv7W42/nitime/setup.py", line 17, in <module>
        exec(f.read())
      File "<string>", line 2, in <module>
      File "nitime/__init__.py", line 26, in <module>
        from . import algorithms
      File "nitime/algorithms/__init__.py", line 55, in <module>
        from nitime.algorithms.spectral import *
      File "nitime/algorithms/spectral.py", line 10, in <module>
        import numpy as np
    ImportError: No module named numpy
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Dv7W42/nitime/
(nitime_test)rwblair@afterhours:~$
```

Let me know if you need any additional information.

**Comment by jimmypeich** [comment]
I just hit the issue and I believe it is related to a "typo" in the version.py that causes some deeper modules to be loaded when reading the version and forcing a dependency on numpy before installing nitime:

```"""nitime version/release information"""
from nitime.six.moves import map
```
Removing the above line should fix the dependency issue ( I believe the standard python `map` is desired instead)

**Comment by arokem** [comment]
Yes -- that makes perfect sense. Importing six from within nitime triggers the numpy import, which can't be completed. I'll take a look at the PR.

**Comment by mihaic** [comment]
@arokem, could you please make a PyPI release that includes the fix for this issue?

**Comment by arokem** [comment]
Yes. Will do. Thanks for the reminder.

**Comment by arokem** [comment]
OK - @mihaic : I've uploaded 0.7 to pip 

(things a bit slow up there, so far only a source tar file, but I am also trying to upload wheels)

**Comment by mihaic** [comment]
Thank you for the release. It really helps our project.

**Comment by arokem** [comment]
Out of curiosity, what project is this, and how are you using nitime within it? I never know who is using this (and I am not really doing time-series analysis much these days, hence the relative silence here...). Thanks!

**Comment by mihaic** [comment]
It is an fMRI data simulator:
https://github.com/IntelPNI/brainiak/blob/master/brainiak/utils/fmrisim.py
